apiVersion: v2
name: ptolemy
description: Versioned geospatial data store with PostGIS
type: application
version: 0.2.0
appVersion: "0.2.1"
keywords:
  - geospatial
  - postgis
  - versioning
  - vector-data
maintainers:
  - name: GeoLang
